export const textsExample = [
  { id: 1, owner: "user", message: "Hello!" },
  { id: 2, owner: "colleague", message: "Hi!" },
  { id: 3, owner: "user", message: "How are you doing?" },
  { id: 4, owner: "colleague", message: "I'm doing good. how about you?" },
  { id: 5, owner: "user", message: "Im good?" },
  { id: 6, owner: "colleague", message: "So what is going on bro?" },
  { id: 8, owner: "colleague", message: "How is your coding going" },
  { id: 9, owner: "user", message: "I will have a break through oneday" },
  { id: 10, owner: "colleague", message: "Really!" },
  { id: 11, owner: "user", message: "I know it" },
  { id: 12, owner: "user", message: "I can feel it coming" },
  { id: 13, owner: "user", message: "You mark it somewhere" },
  {
    id: 14,
    owner: "colleague",
    message: "That is great... just keep working hard",
  },
  { id: 15, owner: "colleague", message: "It will pay off" },
  { id: 16, owner: "user", message: "Yh i know right" },
  { id: 17, owner: "colleague", message: "yeah" },
  { id: 18, owner: "user", message: "Anyway, i have to go" },
  { id: 19, owner: "colleague", message: "okay bro, see you later" },
  { id: 20, owner: "user", message: "Alright.. Bye!" },
  { id: 21, owner: "colleague", message: "Bye!" },
];
